using System;

namespace Maple2.Trigger._02000318_bf {
    public static class _shipmove_02 {
        public static readonly Func<ITriggerContext, TriggerState> Start = context => new StateSetting(context);

        private class StateSetting : TriggerState {
            internal StateSetting(ITriggerContext context) : base(context) { }

            public override void OnEnter() {
                context.SetInteractObject(arg1: new int[] {10001046}, arg2: 0);
                context.SetSkill(arg1: new int[] {7000}, arg2: false);
                context.SetEffect(arg1: new int[] {6000}, arg2: false);
                context.SetEffect(arg1: new int[] {6001}, arg2: false);
                context.SetBreakable(arg1: new int[] {4000}, arg2: false);
                context.SetBreakable(arg1: new int[] {4001}, arg2: false);
                context.SetBreakable(arg1: new int[] {4002}, arg2: false);
                context.SetBreakable(arg1: new int[] {4003}, arg2: false);
                context.SetBreakable(arg1: new int[] {4004}, arg2: false);
                context.SetBreakable(arg1: new int[] {4005}, arg2: false);
                context.SetBreakable(arg1: new int[] {4006}, arg2: false);
                context.SetBreakable(arg1: new int[] {4007}, arg2: false);
                context.SetBreakable(arg1: new int[] {4008}, arg2: false);
                context.SetBreakable(arg1: new int[] {4009}, arg2: false);
                context.SetBreakable(arg1: new int[] {4010}, arg2: false);
                context.SetBreakable(arg1: new int[] {4011}, arg2: false);
                context.SetBreakable(arg1: new int[] {4012}, arg2: false);
                context.SetBreakable(arg1: new int[] {4013}, arg2: false);
                context.SetBreakable(arg1: new int[] {4014}, arg2: false);
                context.SetBreakable(arg1: new int[] {4015}, arg2: false);
                context.SetBreakable(arg1: new int[] {4016}, arg2: false);
                context.SetBreakable(arg1: new int[] {4017}, arg2: false);
                context.SetBreakable(arg1: new int[] {4018}, arg2: false);
                context.SetBreakable(arg1: new int[] {4019}, arg2: false);
                context.SetBreakable(arg1: new int[] {4020}, arg2: false);
                context.SetBreakable(arg1: new int[] {4021}, arg2: false);
                context.SetBreakable(arg1: new int[] {4022}, arg2: false);
                context.SetBreakable(arg1: new int[] {4023}, arg2: false);
                context.SetBreakable(arg1: new int[] {4024}, arg2: false);
                context.SetBreakable(arg1: new int[] {4025}, arg2: false);
                context.SetBreakable(arg1: new int[] {4026}, arg2: false);
                context.SetBreakable(arg1: new int[] {4027}, arg2: false);
                context.SetBreakable(arg1: new int[] {4028}, arg2: false);
                context.SetBreakable(arg1: new int[] {4029}, arg2: false);
                context.SetBreakable(arg1: new int[] {4030}, arg2: false);
                context.SetBreakable(arg1: new int[] {4031}, arg2: false);
                context.SetBreakable(arg1: new int[] {4032}, arg2: false);
                context.SetBreakable(arg1: new int[] {4033}, arg2: false);
                context.SetBreakable(arg1: new int[] {4034}, arg2: false);
                context.SetBreakable(arg1: new int[] {4035}, arg2: false);
                context.SetBreakable(arg1: new int[] {4036}, arg2: false);
                context.SetBreakable(arg1: new int[] {4037}, arg2: false);
                context.SetBreakable(arg1: new int[] {4038}, arg2: false);
                context.SetBreakable(arg1: new int[] {4039}, arg2: false);
                context.SetBreakable(arg1: new int[] {4040}, arg2: false);
                context.SetBreakable(arg1: new int[] {4041}, arg2: false);
                context.SetBreakable(arg1: new int[] {4042}, arg2: false);
                context.SetBreakable(arg1: new int[] {4043}, arg2: false);
                context.SetBreakable(arg1: new int[] {4044}, arg2: false);
                context.SetBreakable(arg1: new int[] {4045}, arg2: false);
                context.SetBreakable(arg1: new int[] {4046}, arg2: false);
                context.SetBreakable(arg1: new int[] {4047}, arg2: false);
                context.SetBreakable(arg1: new int[] {4048}, arg2: false);
                context.SetBreakable(arg1: new int[] {4049}, arg2: false);
                context.SetBreakable(arg1: new int[] {4050}, arg2: false);
                context.SetBreakable(arg1: new int[] {4051}, arg2: false);
                context.SetBreakable(arg1: new int[] {4052}, arg2: false);
                context.SetBreakable(arg1: new int[] {4053}, arg2: false);
                context.SetBreakable(arg1: new int[] {4054}, arg2: false);
                context.SetBreakable(arg1: new int[] {4055}, arg2: false);
                context.SetBreakable(arg1: new int[] {4056}, arg2: false);
                context.SetBreakable(arg1: new int[] {4057}, arg2: false);
                context.SetBreakable(arg1: new int[] {4058}, arg2: false);
                context.SetBreakable(arg1: new int[] {4059}, arg2: false);
                context.SetBreakable(arg1: new int[] {4060}, arg2: false);
                context.SetBreakable(arg1: new int[] {4061}, arg2: false);
                context.SetBreakable(arg1: new int[] {4062}, arg2: false);
                context.SetBreakable(arg1: new int[] {4063}, arg2: false);
                context.SetBreakable(arg1: new int[] {4064}, arg2: false);
                context.SetBreakable(arg1: new int[] {4065}, arg2: false);
                context.SetBreakable(arg1: new int[] {4066}, arg2: false);
                context.SetBreakable(arg1: new int[] {4067}, arg2: false);
                context.SetBreakable(arg1: new int[] {4068}, arg2: false);
                context.SetBreakable(arg1: new int[] {4069}, arg2: false);
                context.SetBreakable(arg1: new int[] {4070}, arg2: false);
                context.SetBreakable(arg1: new int[] {4071}, arg2: false);
                context.SetBreakable(arg1: new int[] {4072}, arg2: false);
                context.SetBreakable(arg1: new int[] {4073}, arg2: false);
                context.SetBreakable(arg1: new int[] {4074}, arg2: false);
                context.SetBreakable(arg1: new int[] {4075}, arg2: false);
                context.SetBreakable(arg1: new int[] {4076}, arg2: false);
                context.SetBreakable(arg1: new int[] {4077}, arg2: false);
                context.SetBreakable(arg1: new int[] {4078}, arg2: false);
                context.SetBreakable(arg1: new int[] {4079}, arg2: false);
                context.SetBreakable(arg1: new int[] {4080}, arg2: false);
                context.SetBreakable(arg1: new int[] {4081}, arg2: false);
                context.SetBreakable(arg1: new int[] {4082}, arg2: false);
                context.SetBreakable(arg1: new int[] {4083}, arg2: false);
                context.SetBreakable(arg1: new int[] {4084}, arg2: false);
                context.SetBreakable(arg1: new int[] {4085}, arg2: false);
                context.SetBreakable(arg1: new int[] {4086}, arg2: false);
                context.SetBreakable(arg1: new int[] {4087}, arg2: false);
                context.SetBreakable(arg1: new int[] {4088}, arg2: false);
                context.SetBreakable(arg1: new int[] {4089}, arg2: false);
                context.SetBreakable(arg1: new int[] {4090}, arg2: false);
                context.SetBreakable(arg1: new int[] {4091}, arg2: false);
                context.SetBreakable(arg1: new int[] {4092}, arg2: false);
                context.SetBreakable(arg1: new int[] {4093}, arg2: false);
                context.SetBreakable(arg1: new int[] {4094}, arg2: false);
                context.SetBreakable(arg1: new int[] {4095}, arg2: false);
                context.SetBreakable(arg1: new int[] {4096}, arg2: false);
                context.SetBreakable(arg1: new int[] {4097}, arg2: false);
                context.SetBreakable(arg1: new int[] {4098}, arg2: false);
                context.SetBreakable(arg1: new int[] {4099}, arg2: false);
                context.SetBreakable(arg1: new int[] {4100}, arg2: false);
                context.SetBreakable(arg1: new int[] {4101}, arg2: false);
                context.SetBreakable(arg1: new int[] {4102}, arg2: false);
                context.SetBreakable(arg1: new int[] {4103}, arg2: false);
                context.SetBreakable(arg1: new int[] {4104}, arg2: false);
                context.SetBreakable(arg1: new int[] {4105}, arg2: false);
                context.SetBreakable(arg1: new int[] {4106}, arg2: false);
                context.SetBreakable(arg1: new int[] {4107}, arg2: false);
                context.SetBreakable(arg1: new int[] {4108}, arg2: false);
                context.SetBreakable(arg1: new int[] {4109}, arg2: false);
                context.SetBreakable(arg1: new int[] {4110}, arg2: false);
                context.SetBreakable(arg1: new int[] {4111}, arg2: false);
                context.SetBreakable(arg1: new int[] {4112}, arg2: false);
                context.SetBreakable(arg1: new int[] {4113}, arg2: false);
                context.SetBreakable(arg1: new int[] {4114}, arg2: false);
                context.SetBreakable(arg1: new int[] {4115}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4000}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4001}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4002}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4003}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4004}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4005}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4006}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4007}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4008}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4009}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4010}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4011}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4012}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4013}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4014}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4015}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4016}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4017}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4018}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4019}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4020}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4021}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4022}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4023}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4024}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4025}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4026}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4027}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4028}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4029}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4030}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4031}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4032}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4033}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4034}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4035}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4036}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4037}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4038}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4039}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4040}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4041}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4042}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4043}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4044}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4045}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4046}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4047}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4048}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4049}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4050}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4051}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4052}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4053}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4054}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4055}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4056}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4057}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4058}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4059}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4060}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4061}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4062}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4063}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4064}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4065}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4066}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4067}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4068}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4069}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4070}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4071}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4072}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4073}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4074}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4075}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4076}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4077}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4078}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4079}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4080}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4081}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4082}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4083}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4084}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4085}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4086}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4087}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4088}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4089}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4090}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4091}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4092}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4093}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4094}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4095}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4096}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4097}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4098}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4099}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4100}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4101}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4102}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4103}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4104}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4105}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4106}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4107}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4108}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4109}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4110}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4111}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4112}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4113}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4114}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4115}, arg2: false);
                context.SetUserValue(key: "ShipSet", value: 0);
            }

            public override void Execute() {
                if (context.UserValue(key: "ShipSet", value: 1)) {
                    context.State = new StateMoveShip01(context);
                    return;
                }
            }

            public override void OnExit() { }
        }

        private class StateMoveShip01 : TriggerState {
            internal StateMoveShip01(ITriggerContext context) : base(context) { }

            public override void OnEnter() {
                context.SetVisibleBreakableObject(arg1: new int[] {4000}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4001}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4002}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4003}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4004}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4005}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4006}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4007}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4008}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4009}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4010}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4011}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4012}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4013}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4014}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4015}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4016}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4017}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4018}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4019}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4020}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4021}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4022}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4023}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4024}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4025}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4026}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4027}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4028}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4029}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4030}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4031}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4032}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4033}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4034}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4035}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4036}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4037}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4038}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4039}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4040}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4041}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4042}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4043}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4044}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4045}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4046}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4047}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4048}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4049}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4050}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4051}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4052}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4053}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4054}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4055}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4056}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4057}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4058}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4059}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4060}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4061}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4062}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4063}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4064}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4065}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4066}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4067}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4068}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4069}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4070}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4071}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4072}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4073}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4074}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4075}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4076}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4077}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4078}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4079}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4080}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4081}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4082}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4083}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4084}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4085}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4086}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4087}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4088}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4089}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4090}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4091}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4092}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4093}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4094}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4095}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4096}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4097}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4098}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4099}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4100}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4101}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4102}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4103}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4104}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4105}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4106}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4107}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4108}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4109}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4110}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4111}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4112}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4113}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4114}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4115}, arg2: true);
                context.SetInteractObject(arg1: new int[] {10001046}, arg2: 1);
                context.PlaySystemSoundInBox(arg1: new int[] {102}, arg2: "System_ShowGuideSummary_01");
                context.ShowGuideSummary(entityID: 20031803, textID: 20031803);
            }

            public override void Execute() {
                if (context.ObjectInteracted(arg1: new int[] {10001046}, arg2: 0)) {
                    context.State = new StateShipMove02(context);
                    return;
                }
            }

            public override void OnExit() { }
        }

        private class StateShipMove02 : TriggerState {
            internal StateShipMove02(ITriggerContext context) : base(context) { }

            public override void OnEnter() {
                context.SetEffect(arg1: new int[] {6001}, arg2: true);
                context.HideGuideSummary(entityID: 20031803);
                context.SetUserValue(triggerID: 1, key: "ShipMove", value: 1);
                context.SetBreakable(arg1: new int[] {4000}, arg2: true);
                context.SetBreakable(arg1: new int[] {4001}, arg2: true);
                context.SetBreakable(arg1: new int[] {4002}, arg2: true);
                context.SetBreakable(arg1: new int[] {4003}, arg2: true);
                context.SetBreakable(arg1: new int[] {4004}, arg2: true);
                context.SetBreakable(arg1: new int[] {4005}, arg2: true);
                context.SetBreakable(arg1: new int[] {4006}, arg2: true);
                context.SetBreakable(arg1: new int[] {4007}, arg2: true);
                context.SetBreakable(arg1: new int[] {4008}, arg2: true);
                context.SetBreakable(arg1: new int[] {4009}, arg2: true);
                context.SetBreakable(arg1: new int[] {4010}, arg2: true);
                context.SetBreakable(arg1: new int[] {4011}, arg2: true);
                context.SetBreakable(arg1: new int[] {4012}, arg2: true);
                context.SetBreakable(arg1: new int[] {4013}, arg2: true);
                context.SetBreakable(arg1: new int[] {4014}, arg2: true);
                context.SetBreakable(arg1: new int[] {4015}, arg2: true);
                context.SetBreakable(arg1: new int[] {4016}, arg2: true);
                context.SetBreakable(arg1: new int[] {4017}, arg2: true);
                context.SetBreakable(arg1: new int[] {4018}, arg2: true);
                context.SetBreakable(arg1: new int[] {4019}, arg2: true);
                context.SetBreakable(arg1: new int[] {4020}, arg2: true);
                context.SetBreakable(arg1: new int[] {4021}, arg2: true);
                context.SetBreakable(arg1: new int[] {4022}, arg2: true);
                context.SetBreakable(arg1: new int[] {4023}, arg2: true);
                context.SetBreakable(arg1: new int[] {4024}, arg2: true);
                context.SetBreakable(arg1: new int[] {4025}, arg2: true);
                context.SetBreakable(arg1: new int[] {4026}, arg2: true);
                context.SetBreakable(arg1: new int[] {4027}, arg2: true);
                context.SetBreakable(arg1: new int[] {4028}, arg2: true);
                context.SetBreakable(arg1: new int[] {4029}, arg2: true);
                context.SetBreakable(arg1: new int[] {4030}, arg2: true);
                context.SetBreakable(arg1: new int[] {4031}, arg2: true);
                context.SetBreakable(arg1: new int[] {4032}, arg2: true);
                context.SetBreakable(arg1: new int[] {4033}, arg2: true);
                context.SetBreakable(arg1: new int[] {4034}, arg2: true);
                context.SetBreakable(arg1: new int[] {4035}, arg2: true);
                context.SetBreakable(arg1: new int[] {4036}, arg2: true);
                context.SetBreakable(arg1: new int[] {4037}, arg2: true);
                context.SetBreakable(arg1: new int[] {4038}, arg2: true);
                context.SetBreakable(arg1: new int[] {4039}, arg2: true);
                context.SetBreakable(arg1: new int[] {4040}, arg2: true);
                context.SetBreakable(arg1: new int[] {4041}, arg2: true);
                context.SetBreakable(arg1: new int[] {4042}, arg2: true);
                context.SetBreakable(arg1: new int[] {4043}, arg2: true);
                context.SetBreakable(arg1: new int[] {4044}, arg2: true);
                context.SetBreakable(arg1: new int[] {4045}, arg2: true);
                context.SetBreakable(arg1: new int[] {4046}, arg2: true);
                context.SetBreakable(arg1: new int[] {4047}, arg2: true);
                context.SetBreakable(arg1: new int[] {4048}, arg2: true);
                context.SetBreakable(arg1: new int[] {4049}, arg2: true);
                context.SetBreakable(arg1: new int[] {4050}, arg2: true);
                context.SetBreakable(arg1: new int[] {4051}, arg2: true);
                context.SetBreakable(arg1: new int[] {4052}, arg2: true);
                context.SetBreakable(arg1: new int[] {4053}, arg2: true);
                context.SetBreakable(arg1: new int[] {4054}, arg2: true);
                context.SetBreakable(arg1: new int[] {4055}, arg2: true);
                context.SetBreakable(arg1: new int[] {4056}, arg2: true);
                context.SetBreakable(arg1: new int[] {4057}, arg2: true);
                context.SetBreakable(arg1: new int[] {4058}, arg2: true);
                context.SetBreakable(arg1: new int[] {4059}, arg2: true);
                context.SetBreakable(arg1: new int[] {4060}, arg2: true);
                context.SetBreakable(arg1: new int[] {4061}, arg2: true);
                context.SetBreakable(arg1: new int[] {4062}, arg2: true);
                context.SetBreakable(arg1: new int[] {4063}, arg2: true);
                context.SetBreakable(arg1: new int[] {4064}, arg2: true);
                context.SetBreakable(arg1: new int[] {4065}, arg2: true);
                context.SetBreakable(arg1: new int[] {4066}, arg2: true);
                context.SetBreakable(arg1: new int[] {4067}, arg2: true);
                context.SetBreakable(arg1: new int[] {4068}, arg2: true);
                context.SetBreakable(arg1: new int[] {4069}, arg2: true);
                context.SetBreakable(arg1: new int[] {4070}, arg2: true);
                context.SetBreakable(arg1: new int[] {4071}, arg2: true);
                context.SetBreakable(arg1: new int[] {4072}, arg2: true);
                context.SetBreakable(arg1: new int[] {4073}, arg2: true);
                context.SetBreakable(arg1: new int[] {4074}, arg2: true);
                context.SetBreakable(arg1: new int[] {4075}, arg2: true);
                context.SetBreakable(arg1: new int[] {4076}, arg2: true);
                context.SetBreakable(arg1: new int[] {4077}, arg2: true);
                context.SetBreakable(arg1: new int[] {4078}, arg2: true);
                context.SetBreakable(arg1: new int[] {4079}, arg2: true);
                context.SetBreakable(arg1: new int[] {4080}, arg2: true);
                context.SetBreakable(arg1: new int[] {4081}, arg2: true);
                context.SetBreakable(arg1: new int[] {4082}, arg2: true);
                context.SetBreakable(arg1: new int[] {4083}, arg2: true);
                context.SetBreakable(arg1: new int[] {4084}, arg2: true);
                context.SetBreakable(arg1: new int[] {4085}, arg2: true);
                context.SetBreakable(arg1: new int[] {4086}, arg2: true);
                context.SetBreakable(arg1: new int[] {4087}, arg2: true);
                context.SetBreakable(arg1: new int[] {4088}, arg2: true);
                context.SetBreakable(arg1: new int[] {4089}, arg2: true);
                context.SetBreakable(arg1: new int[] {4090}, arg2: true);
                context.SetBreakable(arg1: new int[] {4091}, arg2: true);
                context.SetBreakable(arg1: new int[] {4092}, arg2: true);
                context.SetBreakable(arg1: new int[] {4093}, arg2: true);
                context.SetBreakable(arg1: new int[] {4094}, arg2: true);
                context.SetBreakable(arg1: new int[] {4095}, arg2: true);
                context.SetBreakable(arg1: new int[] {4096}, arg2: true);
                context.SetBreakable(arg1: new int[] {4097}, arg2: true);
                context.SetBreakable(arg1: new int[] {4098}, arg2: true);
                context.SetBreakable(arg1: new int[] {4099}, arg2: true);
                context.SetBreakable(arg1: new int[] {4100}, arg2: true);
                context.SetBreakable(arg1: new int[] {4101}, arg2: true);
                context.SetBreakable(arg1: new int[] {4102}, arg2: true);
                context.SetBreakable(arg1: new int[] {4103}, arg2: true);
                context.SetBreakable(arg1: new int[] {4104}, arg2: true);
                context.SetBreakable(arg1: new int[] {4105}, arg2: true);
                context.SetBreakable(arg1: new int[] {4106}, arg2: true);
                context.SetBreakable(arg1: new int[] {4107}, arg2: true);
                context.SetBreakable(arg1: new int[] {4108}, arg2: true);
                context.SetBreakable(arg1: new int[] {4109}, arg2: true);
                context.SetBreakable(arg1: new int[] {4110}, arg2: true);
                context.SetBreakable(arg1: new int[] {4111}, arg2: true);
                context.SetBreakable(arg1: new int[] {4112}, arg2: true);
                context.SetBreakable(arg1: new int[] {4113}, arg2: true);
                context.SetBreakable(arg1: new int[] {4114}, arg2: true);
                context.SetBreakable(arg1: new int[] {4115}, arg2: true);
            }

            public override void Execute() {
                if (context.WaitTick(waitTick: 3000)) {
                    context.State = new StateShipMove03(context);
                    return;
                }
            }

            public override void OnExit() { }
        }

        private class StateShipMove03 : TriggerState {
            internal StateShipMove03(ITriggerContext context) : base(context) { }

            public override void OnEnter() {
                context.SetEffect(arg1: new int[] {6001}, arg2: false);
                context.SetSkill(arg1: new int[] {7000}, arg2: true);
                context.SetEffect(arg1: new int[] {6000}, arg2: true);
            }

            public override void Execute() {
                if (context.WaitTick(waitTick: 19000)) {
                    context.State = new StateResetShip00(context);
                    return;
                }
            }

            public override void OnExit() { }
        }

        private class StateResetShip00 : TriggerState {
            internal StateResetShip00(ITriggerContext context) : base(context) { }

            public override void OnEnter() {
                context.SetInteractObject(arg1: new int[] {10001046}, arg2: 0);
                context.SetBreakable(arg1: new int[] {4000}, arg2: false);
                context.SetBreakable(arg1: new int[] {4001}, arg2: false);
                context.SetBreakable(arg1: new int[] {4002}, arg2: false);
                context.SetBreakable(arg1: new int[] {4003}, arg2: false);
                context.SetBreakable(arg1: new int[] {4004}, arg2: false);
                context.SetBreakable(arg1: new int[] {4005}, arg2: false);
                context.SetBreakable(arg1: new int[] {4006}, arg2: false);
                context.SetBreakable(arg1: new int[] {4007}, arg2: false);
                context.SetBreakable(arg1: new int[] {4008}, arg2: false);
                context.SetBreakable(arg1: new int[] {4009}, arg2: false);
                context.SetBreakable(arg1: new int[] {4010}, arg2: false);
                context.SetBreakable(arg1: new int[] {4011}, arg2: false);
                context.SetBreakable(arg1: new int[] {4012}, arg2: false);
                context.SetBreakable(arg1: new int[] {4013}, arg2: false);
                context.SetBreakable(arg1: new int[] {4014}, arg2: false);
                context.SetBreakable(arg1: new int[] {4015}, arg2: false);
                context.SetBreakable(arg1: new int[] {4016}, arg2: false);
                context.SetBreakable(arg1: new int[] {4017}, arg2: false);
                context.SetBreakable(arg1: new int[] {4018}, arg2: false);
                context.SetBreakable(arg1: new int[] {4019}, arg2: false);
                context.SetBreakable(arg1: new int[] {4020}, arg2: false);
                context.SetBreakable(arg1: new int[] {4021}, arg2: false);
                context.SetBreakable(arg1: new int[] {4022}, arg2: false);
                context.SetBreakable(arg1: new int[] {4023}, arg2: false);
                context.SetBreakable(arg1: new int[] {4024}, arg2: false);
                context.SetBreakable(arg1: new int[] {4025}, arg2: false);
                context.SetBreakable(arg1: new int[] {4026}, arg2: false);
                context.SetBreakable(arg1: new int[] {4027}, arg2: false);
                context.SetBreakable(arg1: new int[] {4028}, arg2: false);
                context.SetBreakable(arg1: new int[] {4029}, arg2: false);
                context.SetBreakable(arg1: new int[] {4030}, arg2: false);
                context.SetBreakable(arg1: new int[] {4031}, arg2: false);
                context.SetBreakable(arg1: new int[] {4032}, arg2: false);
                context.SetBreakable(arg1: new int[] {4033}, arg2: false);
                context.SetBreakable(arg1: new int[] {4034}, arg2: false);
                context.SetBreakable(arg1: new int[] {4035}, arg2: false);
                context.SetBreakable(arg1: new int[] {4036}, arg2: false);
                context.SetBreakable(arg1: new int[] {4037}, arg2: false);
                context.SetBreakable(arg1: new int[] {4038}, arg2: false);
                context.SetBreakable(arg1: new int[] {4039}, arg2: false);
                context.SetBreakable(arg1: new int[] {4040}, arg2: false);
                context.SetBreakable(arg1: new int[] {4041}, arg2: false);
                context.SetBreakable(arg1: new int[] {4042}, arg2: false);
                context.SetBreakable(arg1: new int[] {4043}, arg2: false);
                context.SetBreakable(arg1: new int[] {4044}, arg2: false);
                context.SetBreakable(arg1: new int[] {4045}, arg2: false);
                context.SetBreakable(arg1: new int[] {4046}, arg2: false);
                context.SetBreakable(arg1: new int[] {4047}, arg2: false);
                context.SetBreakable(arg1: new int[] {4048}, arg2: false);
                context.SetBreakable(arg1: new int[] {4049}, arg2: false);
                context.SetBreakable(arg1: new int[] {4050}, arg2: false);
                context.SetBreakable(arg1: new int[] {4051}, arg2: false);
                context.SetBreakable(arg1: new int[] {4052}, arg2: false);
                context.SetBreakable(arg1: new int[] {4053}, arg2: false);
                context.SetBreakable(arg1: new int[] {4054}, arg2: false);
                context.SetBreakable(arg1: new int[] {4055}, arg2: false);
                context.SetBreakable(arg1: new int[] {4056}, arg2: false);
                context.SetBreakable(arg1: new int[] {4057}, arg2: false);
                context.SetBreakable(arg1: new int[] {4058}, arg2: false);
                context.SetBreakable(arg1: new int[] {4059}, arg2: false);
                context.SetBreakable(arg1: new int[] {4060}, arg2: false);
                context.SetBreakable(arg1: new int[] {4061}, arg2: false);
                context.SetBreakable(arg1: new int[] {4062}, arg2: false);
                context.SetBreakable(arg1: new int[] {4063}, arg2: false);
                context.SetBreakable(arg1: new int[] {4064}, arg2: false);
                context.SetBreakable(arg1: new int[] {4065}, arg2: false);
                context.SetBreakable(arg1: new int[] {4066}, arg2: false);
                context.SetBreakable(arg1: new int[] {4067}, arg2: false);
                context.SetBreakable(arg1: new int[] {4068}, arg2: false);
                context.SetBreakable(arg1: new int[] {4069}, arg2: false);
                context.SetBreakable(arg1: new int[] {4070}, arg2: false);
                context.SetBreakable(arg1: new int[] {4071}, arg2: false);
                context.SetBreakable(arg1: new int[] {4072}, arg2: false);
                context.SetBreakable(arg1: new int[] {4073}, arg2: false);
                context.SetBreakable(arg1: new int[] {4074}, arg2: false);
                context.SetBreakable(arg1: new int[] {4075}, arg2: false);
                context.SetBreakable(arg1: new int[] {4076}, arg2: false);
                context.SetBreakable(arg1: new int[] {4077}, arg2: false);
                context.SetBreakable(arg1: new int[] {4078}, arg2: false);
                context.SetBreakable(arg1: new int[] {4079}, arg2: false);
                context.SetBreakable(arg1: new int[] {4080}, arg2: false);
                context.SetBreakable(arg1: new int[] {4081}, arg2: false);
                context.SetBreakable(arg1: new int[] {4082}, arg2: false);
                context.SetBreakable(arg1: new int[] {4083}, arg2: false);
                context.SetBreakable(arg1: new int[] {4084}, arg2: false);
                context.SetBreakable(arg1: new int[] {4085}, arg2: false);
                context.SetBreakable(arg1: new int[] {4086}, arg2: false);
                context.SetBreakable(arg1: new int[] {4087}, arg2: false);
                context.SetBreakable(arg1: new int[] {4088}, arg2: false);
                context.SetBreakable(arg1: new int[] {4089}, arg2: false);
                context.SetBreakable(arg1: new int[] {4090}, arg2: false);
                context.SetBreakable(arg1: new int[] {4091}, arg2: false);
                context.SetBreakable(arg1: new int[] {4092}, arg2: false);
                context.SetBreakable(arg1: new int[] {4093}, arg2: false);
                context.SetBreakable(arg1: new int[] {4094}, arg2: false);
                context.SetBreakable(arg1: new int[] {4095}, arg2: false);
                context.SetBreakable(arg1: new int[] {4096}, arg2: false);
                context.SetBreakable(arg1: new int[] {4097}, arg2: false);
                context.SetBreakable(arg1: new int[] {4098}, arg2: false);
                context.SetBreakable(arg1: new int[] {4099}, arg2: false);
                context.SetBreakable(arg1: new int[] {4100}, arg2: false);
                context.SetBreakable(arg1: new int[] {4101}, arg2: false);
                context.SetBreakable(arg1: new int[] {4102}, arg2: false);
                context.SetBreakable(arg1: new int[] {4103}, arg2: false);
                context.SetBreakable(arg1: new int[] {4104}, arg2: false);
                context.SetBreakable(arg1: new int[] {4105}, arg2: false);
                context.SetBreakable(arg1: new int[] {4106}, arg2: false);
                context.SetBreakable(arg1: new int[] {4107}, arg2: false);
                context.SetBreakable(arg1: new int[] {4108}, arg2: false);
                context.SetBreakable(arg1: new int[] {4109}, arg2: false);
                context.SetBreakable(arg1: new int[] {4110}, arg2: false);
                context.SetBreakable(arg1: new int[] {4111}, arg2: false);
                context.SetBreakable(arg1: new int[] {4112}, arg2: false);
                context.SetBreakable(arg1: new int[] {4113}, arg2: false);
                context.SetBreakable(arg1: new int[] {4114}, arg2: false);
                context.SetBreakable(arg1: new int[] {4115}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4000}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4001}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4002}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4003}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4004}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4005}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4006}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4007}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4008}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4009}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4010}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4011}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4012}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4013}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4014}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4015}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4016}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4017}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4018}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4019}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4020}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4021}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4022}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4023}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4024}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4025}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4026}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4027}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4028}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4029}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4030}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4031}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4032}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4033}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4034}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4035}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4036}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4037}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4038}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4039}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4040}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4041}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4042}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4043}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4044}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4045}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4046}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4047}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4048}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4049}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4050}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4051}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4052}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4053}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4054}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4055}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4056}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4057}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4058}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4059}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4060}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4061}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4062}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4063}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4064}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4065}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4066}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4067}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4068}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4069}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4070}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4071}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4072}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4073}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4074}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4075}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4076}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4077}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4078}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4079}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4080}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4081}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4082}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4083}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4084}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4085}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4086}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4087}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4088}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4089}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4090}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4091}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4092}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4093}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4094}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4095}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4096}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4097}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4098}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4099}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4100}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4101}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4102}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4103}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4104}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4105}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4106}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4107}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4108}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4109}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4110}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4111}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4112}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4113}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4114}, arg2: false);
                context.SetVisibleBreakableObject(arg1: new int[] {4115}, arg2: false);
            }

            public override void Execute() {
                if (context.WaitTick(waitTick: 2000)) {
                    context.State = new StateResetShip01(context);
                    return;
                }
            }

            public override void OnExit() { }
        }

        private class StateResetShip01 : TriggerState {
            internal StateResetShip01(ITriggerContext context) : base(context) { }

            public override void OnEnter() {
                context.SetVisibleBreakableObject(arg1: new int[] {4000}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4001}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4002}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4003}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4004}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4005}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4006}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4007}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4008}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4009}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4010}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4011}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4012}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4013}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4014}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4015}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4016}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4017}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4018}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4019}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4020}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4021}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4022}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4023}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4024}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4025}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4026}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4027}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4028}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4029}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4030}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4031}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4032}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4033}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4034}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4035}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4036}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4037}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4038}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4039}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4040}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4041}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4042}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4043}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4044}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4045}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4046}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4047}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4048}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4049}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4050}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4051}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4052}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4053}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4054}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4055}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4056}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4057}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4058}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4059}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4060}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4061}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4062}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4063}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4064}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4065}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4066}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4067}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4068}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4069}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4070}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4071}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4072}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4073}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4074}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4075}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4076}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4077}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4078}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4079}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4080}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4081}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4082}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4083}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4084}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4085}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4086}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4087}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4088}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4089}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4090}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4091}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4092}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4093}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4094}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4095}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4096}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4097}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4098}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4099}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4100}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4101}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4102}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4103}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4104}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4105}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4106}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4107}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4108}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4109}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4110}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4111}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4112}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4113}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4114}, arg2: true);
                context.SetVisibleBreakableObject(arg1: new int[] {4115}, arg2: true);
                context.SetInteractObject(arg1: new int[] {10001046}, arg2: 1);
            }

            public override void Execute() {
                if (context.ObjectInteracted(arg1: new int[] {10001046}, arg2: 0)) {
                    context.State = new StateResetShip02(context);
                    return;
                }
            }

            public override void OnExit() { }
        }

        private class StateResetShip02 : TriggerState {
            internal StateResetShip02(ITriggerContext context) : base(context) { }

            public override void OnEnter() {
                context.SetBreakable(arg1: new int[] {4000}, arg2: true);
                context.SetBreakable(arg1: new int[] {4001}, arg2: true);
                context.SetBreakable(arg1: new int[] {4002}, arg2: true);
                context.SetBreakable(arg1: new int[] {4003}, arg2: true);
                context.SetBreakable(arg1: new int[] {4004}, arg2: true);
                context.SetBreakable(arg1: new int[] {4005}, arg2: true);
                context.SetBreakable(arg1: new int[] {4006}, arg2: true);
                context.SetBreakable(arg1: new int[] {4007}, arg2: true);
                context.SetBreakable(arg1: new int[] {4008}, arg2: true);
                context.SetBreakable(arg1: new int[] {4009}, arg2: true);
                context.SetBreakable(arg1: new int[] {4010}, arg2: true);
                context.SetBreakable(arg1: new int[] {4011}, arg2: true);
                context.SetBreakable(arg1: new int[] {4012}, arg2: true);
                context.SetBreakable(arg1: new int[] {4013}, arg2: true);
                context.SetBreakable(arg1: new int[] {4014}, arg2: true);
                context.SetBreakable(arg1: new int[] {4015}, arg2: true);
                context.SetBreakable(arg1: new int[] {4016}, arg2: true);
                context.SetBreakable(arg1: new int[] {4017}, arg2: true);
                context.SetBreakable(arg1: new int[] {4018}, arg2: true);
                context.SetBreakable(arg1: new int[] {4019}, arg2: true);
                context.SetBreakable(arg1: new int[] {4020}, arg2: true);
                context.SetBreakable(arg1: new int[] {4021}, arg2: true);
                context.SetBreakable(arg1: new int[] {4022}, arg2: true);
                context.SetBreakable(arg1: new int[] {4023}, arg2: true);
                context.SetBreakable(arg1: new int[] {4024}, arg2: true);
                context.SetBreakable(arg1: new int[] {4025}, arg2: true);
                context.SetBreakable(arg1: new int[] {4026}, arg2: true);
                context.SetBreakable(arg1: new int[] {4027}, arg2: true);
                context.SetBreakable(arg1: new int[] {4028}, arg2: true);
                context.SetBreakable(arg1: new int[] {4029}, arg2: true);
                context.SetBreakable(arg1: new int[] {4030}, arg2: true);
                context.SetBreakable(arg1: new int[] {4031}, arg2: true);
                context.SetBreakable(arg1: new int[] {4032}, arg2: true);
                context.SetBreakable(arg1: new int[] {4033}, arg2: true);
                context.SetBreakable(arg1: new int[] {4034}, arg2: true);
                context.SetBreakable(arg1: new int[] {4035}, arg2: true);
                context.SetBreakable(arg1: new int[] {4036}, arg2: true);
                context.SetBreakable(arg1: new int[] {4037}, arg2: true);
                context.SetBreakable(arg1: new int[] {4038}, arg2: true);
                context.SetBreakable(arg1: new int[] {4039}, arg2: true);
                context.SetBreakable(arg1: new int[] {4040}, arg2: true);
                context.SetBreakable(arg1: new int[] {4041}, arg2: true);
                context.SetBreakable(arg1: new int[] {4042}, arg2: true);
                context.SetBreakable(arg1: new int[] {4043}, arg2: true);
                context.SetBreakable(arg1: new int[] {4044}, arg2: true);
                context.SetBreakable(arg1: new int[] {4045}, arg2: true);
                context.SetBreakable(arg1: new int[] {4046}, arg2: true);
                context.SetBreakable(arg1: new int[] {4047}, arg2: true);
                context.SetBreakable(arg1: new int[] {4048}, arg2: true);
                context.SetBreakable(arg1: new int[] {4049}, arg2: true);
                context.SetBreakable(arg1: new int[] {4050}, arg2: true);
                context.SetBreakable(arg1: new int[] {4051}, arg2: true);
                context.SetBreakable(arg1: new int[] {4052}, arg2: true);
                context.SetBreakable(arg1: new int[] {4053}, arg2: true);
                context.SetBreakable(arg1: new int[] {4054}, arg2: true);
                context.SetBreakable(arg1: new int[] {4055}, arg2: true);
                context.SetBreakable(arg1: new int[] {4056}, arg2: true);
                context.SetBreakable(arg1: new int[] {4057}, arg2: true);
                context.SetBreakable(arg1: new int[] {4058}, arg2: true);
                context.SetBreakable(arg1: new int[] {4059}, arg2: true);
                context.SetBreakable(arg1: new int[] {4060}, arg2: true);
                context.SetBreakable(arg1: new int[] {4061}, arg2: true);
                context.SetBreakable(arg1: new int[] {4062}, arg2: true);
                context.SetBreakable(arg1: new int[] {4063}, arg2: true);
                context.SetBreakable(arg1: new int[] {4064}, arg2: true);
                context.SetBreakable(arg1: new int[] {4065}, arg2: true);
                context.SetBreakable(arg1: new int[] {4066}, arg2: true);
                context.SetBreakable(arg1: new int[] {4067}, arg2: true);
                context.SetBreakable(arg1: new int[] {4068}, arg2: true);
                context.SetBreakable(arg1: new int[] {4069}, arg2: true);
                context.SetBreakable(arg1: new int[] {4070}, arg2: true);
                context.SetBreakable(arg1: new int[] {4071}, arg2: true);
                context.SetBreakable(arg1: new int[] {4072}, arg2: true);
                context.SetBreakable(arg1: new int[] {4073}, arg2: true);
                context.SetBreakable(arg1: new int[] {4074}, arg2: true);
                context.SetBreakable(arg1: new int[] {4075}, arg2: true);
                context.SetBreakable(arg1: new int[] {4076}, arg2: true);
                context.SetBreakable(arg1: new int[] {4077}, arg2: true);
                context.SetBreakable(arg1: new int[] {4078}, arg2: true);
                context.SetBreakable(arg1: new int[] {4079}, arg2: true);
                context.SetBreakable(arg1: new int[] {4080}, arg2: true);
                context.SetBreakable(arg1: new int[] {4081}, arg2: true);
                context.SetBreakable(arg1: new int[] {4082}, arg2: true);
                context.SetBreakable(arg1: new int[] {4083}, arg2: true);
                context.SetBreakable(arg1: new int[] {4084}, arg2: true);
                context.SetBreakable(arg1: new int[] {4085}, arg2: true);
                context.SetBreakable(arg1: new int[] {4086}, arg2: true);
                context.SetBreakable(arg1: new int[] {4087}, arg2: true);
                context.SetBreakable(arg1: new int[] {4088}, arg2: true);
                context.SetBreakable(arg1: new int[] {4089}, arg2: true);
                context.SetBreakable(arg1: new int[] {4090}, arg2: true);
                context.SetBreakable(arg1: new int[] {4091}, arg2: true);
                context.SetBreakable(arg1: new int[] {4092}, arg2: true);
                context.SetBreakable(arg1: new int[] {4093}, arg2: true);
                context.SetBreakable(arg1: new int[] {4094}, arg2: true);
                context.SetBreakable(arg1: new int[] {4095}, arg2: true);
                context.SetBreakable(arg1: new int[] {4096}, arg2: true);
                context.SetBreakable(arg1: new int[] {4097}, arg2: true);
                context.SetBreakable(arg1: new int[] {4098}, arg2: true);
                context.SetBreakable(arg1: new int[] {4099}, arg2: true);
                context.SetBreakable(arg1: new int[] {4100}, arg2: true);
                context.SetBreakable(arg1: new int[] {4101}, arg2: true);
                context.SetBreakable(arg1: new int[] {4102}, arg2: true);
                context.SetBreakable(arg1: new int[] {4103}, arg2: true);
                context.SetBreakable(arg1: new int[] {4104}, arg2: true);
                context.SetBreakable(arg1: new int[] {4105}, arg2: true);
                context.SetBreakable(arg1: new int[] {4106}, arg2: true);
                context.SetBreakable(arg1: new int[] {4107}, arg2: true);
                context.SetBreakable(arg1: new int[] {4108}, arg2: true);
                context.SetBreakable(arg1: new int[] {4109}, arg2: true);
                context.SetBreakable(arg1: new int[] {4110}, arg2: true);
                context.SetBreakable(arg1: new int[] {4111}, arg2: true);
                context.SetBreakable(arg1: new int[] {4112}, arg2: true);
                context.SetBreakable(arg1: new int[] {4113}, arg2: true);
                context.SetBreakable(arg1: new int[] {4114}, arg2: true);
                context.SetBreakable(arg1: new int[] {4115}, arg2: true);
            }

            public override void Execute() {
                if (context.WaitTick(waitTick: 24000)) {
                    context.State = new StateResetShip01(context);
                    return;
                }
            }

            public override void OnExit() { }
        }
    }
}